### ISSUE TITLE
code inside load function, not execute

### ISSUE THREAD

**Issue by amit-mall** [shinsenter/defer.js#100]
code inside load function is not being execute.
jQuery(window).on('load', function() {
 //not executing
})
window.addEventListener('DOMContentLoaded', (event) => {
 //not executing
})
window.addEventListener("load", function(){
 //not executing
})
document.onload = function(){
 //not executing
})

while .ready is working

**Comment by shinsenter** [comment]
@amit-mall 
All the methods you mentioned can be used to lazyload javascript so there is no need to call it inside the Defer() function.

**Comment by amit-mall** [comment]
Thanks for the response, It means code inside deferred script only executes, after page loads just like code inside $(window).load executes?

**Comment by shinsenter** [comment]
@amit-mall 
Basically you can replace the methods mentioned above with the Defer() function, to lazyload the javascript inside. Defer() improves your website load speed as well as improves SEO scores of Google Search's evaluation for your website.

**Comment by amit-mall** [comment]
ok, thanks
