### ISSUE TITLE
Defer Google Analytics 4 gtag js script

### ISSUE THREAD

**Issue by nafatrue** [shinsenter/defer.js#107]
hi i'm trying to defer gtag Google Analytics 4  js script but no success here is my code
<code>
Defer.js('https://www.googletagmanager.com/gtag/js?id=XXXXX','gtag-js', 10);
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'XXXXX');
</code>

**Comment by shinsenter** [comment]
@nafatrue 
Since GA script will be lazyloaded, so the gtag outside Defer scope may not work until the script fully downloaded.

You may try:

```
<script>
Defer.js(['https://www.googletagmanager.com/gtag/js?id=XXXXX', 'gtag-js', 100, function() {
        window.dataLayer = window.dataLayer || []; 
        function gtag(){dataLayer.push(arguments);} 
        gtag('js', new Date()); 
        gtag('config', 'XXXXX');
    });
</script>
```

**Comment by shinsenter** [comment]
@nafatrue BTW, did you got any error?
