### ISSUE TITLE
From version 3.5 to 3.8 deferjs breaks fontawesome icons

### ISSUE THREAD

**Issue by kressly** [shinsenter/defer.js#140]
I love deferjs and it is the best defer Javascript I have ever used. I should buy the owner a coffee. However, since version 3.5, after version 3.4 I could no longer use deferjs in my adminlte 2 template. Font awesome icons No longer show as soon as I copy the defer plus directly into my code as I use to with version 3.4.

I even waited for other release and recently tried version 3.8 but sadly I still can't get it to work. Is there a fix to this please? I really like this script. It is the best. And I feel like I am missing out on this now.

**Comment by shinsenter** [comment]
Hello @kressly, thank you for your interest in defer.js.

Regarding your issue, could you provide more detailed information or a minimal setup that can reproduce the problem you’re experiencing?

Additionally, which browser are you encountering this issue with?

**Comment by shinsenter** [comment]
@kressly 

Using the [demo files included in this repository](https://github.com/shinsenter/defer.js/tree/main/demo), I was able to confirm that FontAwesome works fine with version 3.8.

<img width="787" alt="Screenshot 2024-10-22 at 10 43 49" src="https://github.com/user-attachments/assets/3e718db6-af60-4bd1-ab49-03c42d0f46e4">


I hope you can share your setup that is currently experiencing the issue.

**Comment by kressly** [comment]
Thank you so much for your answer. I use an old version of font awesome with adminlte 2, it is already embed in it. And i copied and pasted the defer_plus.min.js directly into my page for the version 3.4 and it worked. here is a screenshot.
![1 fw](https://github.com/user-attachments/assets/14b199f0-b9ff-4410-bde6-f64d473f7880)
Now here is the same page with version 3.8
![2 fw](https://github.com/user-attachments/assets/58387d02-d2bf-4ea3-9f09-8ba0bea0fa13)
All i did was to replace the code from 3.4 with 3.8 and as u can see the styling disappeared sort of at places and also most icons from font awesome disappeared. I dont know whether the settings may have changed fro 3.4 to 3.8.

and thank you for an amazing Job we should definately buy you a coffee some day or at the end of this project.

**Comment by shinsenter** [comment]
@kressly Could you show me the JavaScript or HTML snippet you're using to load FontAwesome?

**Comment by shinsenter** [comment]
@kressly 

By the way, I believe that there haven't been many major changes between version 3.4 and 3.8, so you can comfortably continue using version 3.4 if it's working well for your project.

**Comment by kressly** [comment]
Thank you so much for ur response. I am actually using this template 


https://adminlte.io/themes/AdminLTE/index2.html

which can be downloaded for free from here 

https://github.com/TaquitoGazpacho/AdminLTE-2.4.2

there are two folders bower_components\Ionicons and

folder called bower_components\font-awesome\

 

those font are incorporated directly in the design so i use them like this

<i class=" ion-trophy "></i>

the screenshot i sent i thought was font awesome my bad but it was Ionicons rather. MY bad. 

here is a 
![2 fw](https://github.com/user-attachments/assets/4d175a50-cc61-499c-80c1-2db202b985dc)
screenshot from font awesome with version 3.4 
and now in the same design with version 3.8
![1 fw](https://github.com/user-attachments/assets/b722ba59-a2cc-4faa-ac19-5f7c2e189cf4)
as u can see with version 3.8 or from version 3.5 those icons disappear. 

again i only use the copy and paste of the defer_plus.min.js which is amazing.


here is how my code is structured


`<script>
	<?php
//The powerful lazy load of https://github.com/shinsenter/defer.js
//Fichier  dist/defer.plus.min.js	
	?>
	/*!@shinsenter/defer.js@3.4.0*/
!(function(n){function t(e){n.addEventListener(e,z)}function o(e){n.removeEventListener(e,z)}function s(e,n,t){D?C(e,n):(t||s.lazy&&void 0===t?S:L).push(e,n)}function r(e){k.head.appendChild(e)}function i(e,n){q.call(e.attributes)[v](n)}function c(e,n,t,o){return o=(n?k.getElementById(n):o)||k.createElement(e),n&&(o.id=n),t&&(o.onload=t),o}function f(e,n,t){(t=e.src)&&((n=c(m)).rel="preload",n.as=h,n.href=t,(t=e[g](w))&&n[b](w,t),(t=e[g](j))&&n[b](j,t),r(n))}function u(e,n){return q.call((n||k).querySelectorAll(e))}function a(e,n){e.parentNode.replaceChild(n,e)}function l(t,e){u("source,img",t)[v](l),i(t,function(e,n){(n=/^data-(.+)/.exec(e.name))&&t[b](n[1],e.value)}),"string"==typeof e&&e&&(t.className+=" "+e),p in t&&t[p]()}function e(e,n,t){s(function(t){(t=u(e||I))[v](f),(function o(e,n){(e=t[E]())&&((n=c(e.nodeName)).text=e.text,i(e,function(e){"type"!=e.name&&n[b](e.name,e.value)}),n.src&&!n[g]("async")?(n.onload=n.onerror=o,a(e,n)):(a(e,n),o()))})()},n,t)}var d="Defer",m="link",h="script",p="load",y="pageshow",v="forEach",g="getAttribute",b="setAttribute",E="shift",w="crossorigin",j="integrity",x=["mousemove","keydown","touchstart","wheel"],A="on"+y in n?y:p,I=h+"[type=deferjs]",N=n.IntersectionObserver,k=n.document||n,C=n.setTimeout,D=/p/.test(k.readyState),L=[],S=[],q=L.slice,z=function(e,n){for(n=A==e.type?(o(A),D=s,x[v](t),L):(x[v](o),S);n[0];)C(n[E](),n[E]())};e(),s.all=e,s.dom=function(e,n,i,r,c){s(function(t){function o(e){r&&!1===r(e)||l(e,i)}t=!!N&&new N(function(e){e[v](function(e,n){e.isIntersecting&&(t.unobserve(n=e.target),o(n))})},c),u(e||"[data-src]")[v](function(e){e[d]!=s&&(e[d]=s,t?t.observe(e):o(e))})},n,!1)},s.css=function(n,t,e,o,i){s(function(e){(e=c(m,t,o)).rel="stylesheet",e.href=n,r(e)},e,i)},s.js=function(n,t,e,o,i){s(function(e){(e=c(h,t,o)).src=n,r(e)},e,i)},s.reveal=l,n[d]=s,D||t(A)})(this),(function(e,n){n=e.defer=e.Defer,e.deferimg=e.deferiframe=n.dom,e.deferstyle=n.css,e.deferscript=n.js})(this);


	deferiframe('iframe[data-src],[data-style]');
	deferimg('img[data-src],picture,video,audio'); </script>`

when i want to use version 3.8 i only replace the content of the defer.plus.min.js with the part above and i keep 

`deferiframe('iframe[data-src],[data-style]');
	deferimg('img[data-src],picture,video,audio');`

maybe i am doing something not right ?

**Comment by shinsenter** [comment]
@kressly 

I still don’t clearly see where you are implementing lazy loading for FontAwesome. It seems like AdminLTE doesn't have defer.js integrated by default, and you manually modified the HTML code to lazy load resources according to your needs.

It might take quite some time for me to dig through the AdminLTE-2.4.2 source code using the link you provided and pinpoint the exact issue you're facing, and I still recommend you to use the 3.4 version for your project.

**Comment by kressly** [comment]
actually I do not lazy load the font, i only lady load images, css  and iframe and i think since those icons are css based and i lazy load css ... i have combined all my css files into one big file and with the help of ur awesome lazy load i lazy load the God blessed thing men .... i thank God for ur lazy load. U are a blessing to the dev community.

**Comment by kressly** [comment]
please include a link to "buy you a coffe" somewhere so that by the time we are done with our project we could buy you a coffee cos this has been a major blessing to our programming lives. Please make sure there is more than paypal in the links cos some of us in africa, paypal does not work with our country.

**Comment by shinsenter** [comment]
Hi @kressly 


I truly appreciate your generosity in offering to contribute financially to support this small project. However, at the moment, I can only accept donations through PayPal and do not have other methods available. I acknowledge your kindness, and if possible, please consider donating the amount to a local charity in your area instead.

I sincerely thank you for your thoughtful gesture.

**Comment by kressly** [comment]
Our entire team is grateful to God and to you for you work
