### ISSUE TITLE
Request to exclude the optimizations only for amp pages

### ISSUE THREAD

**Issue by nuevaya** [shinsenter/defer.js#21]
**Is your feature request related to a problem? Please describe.**
The amp validator throws a lot of issues when the plugin is active. It is a great plugin and works as is expected.

**Describe the solution you'd like**
I would like to know is it any option to disable the plugin only in amp pages

**Describe alternatives you've considered**

**Additional context**

**Comment by shinsenter** [comment]
The plugin is already configured not to optimize AMP pages. So there may be something broken. Please try using the latest version of defer.php or defer-wordpress and tell me if the problem is solved

**Comment by shinsenter** [comment]
@nuevaya 
Your problem may not concern to this library (defer.js). I will move this issue to defer.php library.

**Comment by nuevaya** [comment]
I have to exclude the plugin from the amp for wp plugin..
Thank you so much

**Comment by shinsenter** [comment]
@nuevaya 
Please update to the latest version of the plugin (v.1.1.7). Hope it fixes your issues.

Note: To archive better result, please disable lazyload and HTML-CSS-JS optimizations by other plugins.

Regards
