### ISSUE TITLE
Conflicts with themes Divi

### ISSUE THREAD

**Issue by minhtran1134** [shinsenter/defer.js#22]
Hi friend, I am using Divi Themes but I have a conflict with the plugin A performant lazy loader (defer.js) developed by your side
                                              
![Screenshot (43)](https://user-images.githubusercontent.com/13937011/55956916-40dfd380-5c8f-11e9-81c3-c923504fcb5b.png)
![Screenshot (44)](https://user-images.githubusercontent.com/13937011/55956917-40dfd380-5c8f-11e9-9bdd-6a9522e487bb.png)
![Screenshot (45)](https://user-images.githubusercontent.com/13937011/55956918-41786a00-5c8f-11e9-984d-2d3b9e430de8.png)

When I activate the plugin, the css and javascript code that I added does not work. Only when I deactivate this plugin will it return to normal.

I also sent a notification to the developer themes, I hope you will fix the error that conflicts with the themes in the next update of this plugin.

**Comment by shinsenter** [comment]
Hi there, your theme's JavaScript seems not work properply with defer.js. Please try turning JavaScript optiomization off in the "My defer.js" screen.

**Comment by minhtran1134** [comment]
thank you support

**Comment by shinsenter** [comment]
Hi @minhtran1134 
I’m sorry that this leads to a very bad experience for the plugin. 

As you said, after turning off my plugin, the problem still occurs, so I mean this potential problem may have arisen from another place.

Please update to the latest version of the plugin (v.1.1.7). Hope it fixes your issues.

Note: To archive better result, please disable lazyload and HTML-CSS-JS optimizations by other plugins.

Regards
