### ISSUE TITLE
Firefox Not loaded

### ISSUE THREAD

**Issue by BlackKite84** [shinsenter/defer.js#23]
on firefox 66.0.3 (64-Bit) all Javascripts not Loaded after Page ist ready.

The Console F12 not Showing javascripts

Testet Local and https://appseeds.net/defer.js/demo.html

**Comment by shinsenter** [comment]
Please tell me which Firefox version that you were using

**Comment by shinsenter** [comment]
Thank you for the feedback, we will try to find the issue with Firefox 66.0.3

**Comment by vqquoc** [comment]
I have similar problems, please help.
Thanks

**Comment by shinsenter** [comment]
@vqquoc I represented the issue on Firefox. I am working to fix it.

**Comment by shinsenter** [comment]
@BlackKite84 @vqquoc 
Firefox problem solved in #24.
Please update your URL to the libraries as below:
https://cdn.jsdelivr.net/npm/@shinsenter/defer.js@1.1.7/dist/defer_plus.min.js

**Comment by shinsenter** [comment]
@BlackKite84 @vqquoc

Please update to the latest version of the plugin (v.1.1.7). Hope it fixes your issues.
Note: To archive better result, please disable lazyload and HTML-CSS-JS optimizations by other plugins.

Regards

**Comment by vqquoc** [comment]
I have updated v1.1.7. it works very well

Thanks @shinsenter

**Comment by shinsenter** [comment]
@vqquoc Thank you for your feedback!
If you like the plugin, please [write a review](https://wordpress.org/support/plugin/shins-pageload-magic/reviews/?filter=5) on the plugin page, or share this plugin to your friends.
