### ISSUE TITLE
Support dynamically added elements

### ISSUE THREAD

**Issue by hacknug** [shinsenter/defer.js#25]
**Describe the bug**
defer.js doesn't work correctly with dynamically added elements

**To Reproduce**
1. Use both `defer.js` and [`swup`](https://github.com/gmrchk/swup) on the same website.
2. Open a page in your browser (everything works fine so far).
3. Click a link to a different page (`swup` will handle the transition)
4. Images won't load inside the refreshed content.

**Expected behavior**
defer should work somewhat similarly to how jQuery handles event delegation:
```js
$(document).on('click', '[data-src]', handleDataSrc)
```

**Desktop (please complete the following information):**
 - OS: macOS v10.14.3
 - Browser: Chrome v73.0.3683.103 (64 bits)

**Additional context**
Disabling swup _solves_ the issue but of course that option is off the table.

**Comment by hacknug** [comment]
This was a mistake on my end. For some reason the event I used to listen for when using swup wasn't being triggered at the right time or at all 🤷‍♂️

**Comment by shinsenter** [comment]
@hacknug 
Thank you for the feedbacks.
To trigger images / media elements which are added dynamically, please call deferimg('img[data-src]') again after the elements were appended to the DOM.
