### ISSUE TITLE
I wanted to know how to prevent images from loading as the user scrolls down the bar, because this is annoying. 

### ISSUE THREAD

**Issue by Giansalero** [shinsenter/defer.js#30]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shinsenter** [comment]
Hi there

You can add an attribute into image tags that you do not want them to be processed by my plugin, like this:
`<img data-ignore src="....." />`
or
`<script data-ignore>......</script>`
