### ISSUE TITLE
Sets incorrect encoding

### ISSUE THREAD

**Issue by Cl0804** [shinsenter/defer.js#31]
**Describe the bug**

**To Reproduce**
1. Install Wordpress and a custom theme of your choice.
2. Ensure header.php has 
`<meta http-equiv="Content-type" content="text/html;charset=UTF-8">`
3. Activate plugin.
4. Open console and see that encoding has been set to ASCII

**Expected behavior**
When function toHtml is called $charset should be UTF-8 however it is not and is being set to ASCII somewhere along the process.

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version Version 74.0.3729.169 (Official Build) (64-bit)

**Additional context**
Plugin works amazing apart from this annoying issue.

**Comment by shinsenter** [comment]
Thank you for your feedback. I will check it out and get back to you as soon as possible.

**Comment by shinsenter** [comment]
This issue was fixed here:
https://github.com/shinsenter/defer-wordpress
