### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by yanivz** [shinsenter/defer.js#33]
**Describe the bug**
page breaks and not working good when jquery in page
**To Reproduce**
every occurence of jquery $ sign got error

**Comment by shinsenter** [comment]
@yanivz which version of defer.js are you using?

**Comment by shinsenter** [comment]
Closed this issue

**Comment by danielrob** [comment]
Is there any better pattern to solve dependency trees than callbacks? 
```
  deferscript("jQuery", false, 80, function() {
    deferscript("slickSlider", false, 0, function() {
      deferscript("balanceText", false, 0, function() {
    });
  });
```

@yanivz you have a number of options to my naive knowledge: 
 - use the callback system like above
 - do [something like this](https://stackoverflow.com/a/21013975/4682556)
 - make your jQuery dependent code register itself to be executed when jQuery is available. e.g.
```
deferscript("jQuery", false, 80, function() {
   window.jQueue = window.jQueue || []
   window.jQueue.forEach(function(script) { script() })
}


if (jQuery) {
   dependentScript(jQuery)
} else {
   window.jQueue = window.jQueue || []
   window.jQueue.push(dependentScript)
}
```
