### ISSUE TITLE
Background Images lazyload not working on IE 11

### ISSUE THREAD

**Issue by nshonda** [shinsenter/defer.js#37]
**Describe the bug**
Lazyload for background images doesn't set style tag on IE11

**To Reproduce**
1. Go to https://appseeds.net/defer.js/wp/optimized on IE 11
2. See Hero Slider
4. No images show

**Expected behavior**
The Hero Slider should display images

**Screenshots**
IE 11

![image](https://user-images.githubusercontent.com/2747573/70181043-ea148780-16bf-11ea-8093-ad107fde4388.jpg)

Chrome 71

![win10_chrome_71](https://user-images.githubusercontent.com/2747573/70181046-ebde4b00-16bf-11ea-84b6-fb21a70183b1.jpg)

**Desktop:**
 - OS: Windows 10
 - Browser: Internet Explorer
 - Version 11

**Comment by shinsenter** [comment]
@nshonda 

Thank you for your support. The pull request will be merged in the next release (this week).

**Comment by shinsenter** [comment]
Merged #39
