### ISSUE TITLE
Does not work with Avada.

### ISSUE THREAD

**Issue by andremarketic** [shinsenter/defer.js#40]
**Describe the bug**
When I activate the plugin, the website breaks in my testimonials section. 
I'm using Avada Theme.

**Comment by shinsenter** [comment]
@andremarketic 

Because this is just a pure javascript library, you need to properly integrate it into your website.

Can you give me the details of the error, such as a red message displayed in the debug tool (like Chrome DevTools)?

**Comment by shinsenter** [comment]
Close #40 because there was no response from issue's owner
