### ISSUE TITLE
Images fallback

### ISSUE THREAD

**Issue by CharlyFrias** [shinsenter/defer.js#41]
I can't find a way to defer an image that has a fallback of the form:

    <img src="image.svg" onerror="this.src='image.png'">

So that functions in old browsers.

Now I am using:

    <script> deferimg ('img [data-src], picture, video, audio') </script>

in the body, and for the images this:

    <img data-src = "image.svg" onerror = "this.src = 'image.png'">

and it works fine in modern browsers but does not put "image, png" in IE8. I have not tried in other old browsers.

Can you help me.

Thanks in advance
Carlos.

**Comment by shinsenter** [comment]
@CharlyFrias 
[defer.js supports IE9+](https://github.com/shinsenter/defer.js#browser-support), so it may not work with IE8 (not tested).

You can try using other lazy-load solutions. I am sorry.
