### ISSUE TITLE
Does this affect Google Tag Manager?

### ISSUE THREAD

**Issue by redlet** [shinsenter/defer.js#43]
They explicitly state that the two segments need to be at the beginning of the head and body elements. It seems to work fine, but I'm wondering if moving everything to the bottom could cause a problem.

Edit: Also, I have a HubSpot form in <script> tags getting moved to the bottom of the page. How do I prevent it from being moved?

**Comment by shinsenter** [comment]
Dear @redlet 

You may put a `data-ignore` attribute to script tag which you do not want my library to optimize it.

By default, the GTM or Google Analyics scripts will be ignored.

**Comment by shinsenter** [comment]
Closed because there was no response.
