### ISSUE TITLE
Ignore code & pre tag when compress html

### ISSUE THREAD

**Issue by khiemle2409** [shinsenter/defer.js#45]
My website is a blog related to code. So when i use orther plugin to highlight my code, it doesn't break line because it is compressed

Solution: ignore pre and code tag when compress html.

Temporary solution: disable compress html

My website: https://khiemle.dev

**Comment by shinsenter** [comment]
@khiemle2409 
This library is just a small JavaScript library, it has no effect on CODE, PRE tags of HTML structure on your website so I don't think this is a bug related to this library.  If you are using a library for Wordpress, [please open an issue here](https://github.com/shinsenter/defer-wordpress/issues).
