### ISSUE TITLE
Some issues with elementor and litespeed

### ISSUE THREAD

**Issue by mrkapable007** [shinsenter/defer.js#47]
**Describe the bug**

An issue with Elementor responsive control when a column is hiding for mobile-only, white space is created and additionally it looks like this is not compatible with elementor and litespeed cache.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shinsenter** [comment]
@mrkapable007 
I think this problem is posted in the wrong repository. It should be posted in the issues section of the Wordpress plugin.

https://github.com/issues
