### ISSUE TITLE
after load Jquery  -  $(window).on('load', function () - without function. 

### ISSUE THREAD

**Issue by dihegroup** [shinsenter/defer.js#49]
we load JQuery 2.2.4 with defer, but after this we cannot use $(window).on('load', function ()). 

Do you know how we can fix it?

**Comment by shinsenter** [comment]
@dihegroup 

Can you tell me how you are currently using this library to lazy-load jquery on your website?

My guess is, maybe the `$(window).on('load', function (){})` is called directly on the page before the jQuery library is actually loaded (that's how lazy-load works). You can try defer your custom javascript too, to make sure it is executed after jQuery has completely loaded.

**Comment by dihegroup** [comment]
`<script src="https://cdn.jsdelivr.net/npm/@shinsenter/defer.js@1.1.11/dist/defer_plus.min.js"></script>
    <script type="deferjs">'IntersectionObserver'in window||deferscript('https://cdn.jsdelivr.net/npm/@shinsenter/defer.js@1.1.11/dist/polyfill.min.js', 'polyfill-js', 1)</script>

   <script type="deferjs">
    deferscript('https://code.jquery.com/jquery-2.2.4.min.js', 'jQuery', 1000, function() {
	    $(document).ready(function(){
			console.log("ready");
		});
        $(window).load(function(){
			console.log("load");
		});
    });	
    </script>`

**Comment by dihegroup** [comment]
console show me: ready, but not load.

**Comment by shinsenter** [comment]
@dihegroup 
All scripts deferred with the library will be run after browser’s “load” event, so maybe your script runs after that, the window.load never runs, and the “load” text wont be shown.
