### ISSUE TITLE
defersmart breaks in IE11

### ISSUE THREAD

**Issue by mnakalay** [shinsenter/defer.js#50]
Hello,

When using the script with defersmart (no manual call) it breaks before of this line:

`tag.onload = tag.onerror = appendtag;`

The appendtag method is never called so the first script (with an src) is moved to the head and then it stops.

TO make it work in IE11 it has to be

`tag.onload = tag.onerror = appendtag();`

But that introduces new issues.

First for some reason, Chromium-based browsers don't like and start breaking. I have no idea why but if you add the parenthesis it stops working for Chrome.

That was easy enough to fix, I did

```
if (window.document.documentMode) {
    // Do IE stuff
    tag.onload = tag.onerror = appendtag();
} else {
    tag.onload = tag.onerror = appendtag;
}
```
And that works. But that brings us to another problem.

IE11 doesn't respect the order for executing scripts. Or to be more accurate it executes inline scripts right away no matter where they are in the head. So if an inline script depends on a remote script, chances are it will throw an error in IE11.

I haven't found a way around that so far

**Comment by shinsenter** [comment]
@mnakalay 
The implementation of the onload and onerror behavior on different browsers is also different, and for non-Chrome-based browsers (such as Internet Explorer) can be a bit of a glitch sometimes.

I have tested this library with IE9 + versions, but have not been able to reproduce the situation you said. Can you tell me more specific error information from IE's developer tools?

**Comment by mnakalay** [comment]
What I have is several script elements with type="deferjs". I let your script do the work automatically.

The first script element is changed to the correct type and that's all, all the others keep the type="deferjs" attribute.

There is no error. Simply the onload callback doesn't run after the first script is modified so none of the other scripts get treated. By using the modification I presented above it works in IE11, Chrome, and Firefox.

**Comment by shinsenter** [comment]
@mnakalay 
I run demo page with IE11 and it just works. All script tags with `type="deferjs"` have executed in expected order.
