### ISSUE TITLE
Handling of multiple script loads

### ISSUE THREAD

**Issue by keyurshah** [shinsenter/defer.js#51]
**Is your feature request related to a problem? Please describe.**
I would like to understand how multiple calls to the same script from deferscript are handled?

I am trying to separate my code into separate components, and each component may load the same javascript from separate points in the application.

If deferscript is called multiple times for the same javascript file, it seems the file is loaded multiple times. Unless I specifiy an id for the script. Not sure if this is the case.

**this seems to load the unpoly script 2 times (based on the console.log)**

https://codepen.io/kjshah/pen/45e013759d68777beafea467ecfd5664?editors=1111

```
    <script src="//cdn.jsdelivr.net/npm/@shinsenter/defer.js/dist/defer_plus.min.js"></script>

<script>  deferscript("//unpkg.com/unpoly@0.62.1/dist/unpoly.min.js")
</script>
<script>  deferscript("//unpkg.com/unpoly@0.62.1/dist/unpoly.min.js")
</script>
```

---

**this seems to load the unpoly script 1 time (based on the console.log)**

https://codepen.io/kjshah/pen/mdPqVzJ

```
    <script src="//cdn.jsdelivr.net/npm/@shinsenter/defer.js/dist/defer_plus.min.js"></script>

<script>  deferscript("//unpkg.com/unpoly@0.62.1/dist/unpoly.min.js",'unpoly-1', 0)
</script>
<script>  deferscript("//unpkg.com/unpoly@0.62.1/dist/unpoly.min.js",'unpoly-2',0)
</script>
```

not sure if this is the purpose of the id. otherwise, is it possible to make sure a script is loaded only one time when not using id?

Thanks.

**Comment by shinsenter** [comment]
@keyurshah 
Thank you for your question.

The argument id of the deferscript () or deferstyle () function is to prevent this library from creating different script tags for instances with the same id (for example, script instance with the same id "jquery" will only be created once. ). However, if you do not declare the id parameter for deferscript () or deferstyle (), different calls of the same script will be made multiple times.

Also, for your problem, you can lazy-load your script files more simply by creating a regular <script> tag with the type="deferjs" attribute:

```
<script src="//cdn.jsdelivr.net/npm/@shinsenter/defer.js/dist/defer_plus.min.js"></script>
<script type="deferjs" src="//your-server/your-script.01.js"></script>
<script type="deferjs" src="//your-server/your-script.02.js"></script>
<script type="deferjs" src="//your-server/your-script.03.js"></script>
```

**Comment by keyurshah** [comment]
thank you for explaining that clearly. that seems to work.  so it's best to always add the id to deferscript to avoid duplicate loading.
