### ISSUE TITLE
Virus found by windows defender in the latest update as soon as it is downloaded

### ISSUE THREAD

**Issue by kressly** [shinsenter/defer.js#57]
In the lastest update, as soon as I download the file from Github, I get a notification of a virus .Kindly check the screenshot bellow. Please before merging a pull request make sure it is virus free
![image](https://user-images.githubusercontent.com/925132/103447847-9391c800-4c88-11eb-8671-fbe7a85c0ddc.png)

**Comment by shinsenter** [comment]
@kressly 
Thank you for your feedback. I will check it carefully

**Comment by shinsenter** [comment]
I checked the package. All clean.
