### ISSUE TITLE
Load on interaction

### ISSUE THREAD

**Issue by peixotorms** [shinsenter/defer.js#72]
Thanks for the great library.
Any chance you could add an option to load scripts only on interaction?

For example, something like:
```
Defer(function() {
  jQuery('div').hide().fadeIn().show();
}, null, null, true); // <- no delay, no callback, but load only on interaction (default false)
```
where true, would only trigger on `'keydown', 'mouseover', 'touchmove', 'touchstart'`

Thank you

**Comment by shinsenter** [comment]
Hey @peixotorms 
No need to use libraries, just use addEventListener.
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

**Comment by shinsenter** [comment]
```html
<script>
  // Show an alert when user scrolled to #scroll_reveal
  Defer.dom('a.my_class', null, null, function(element) {
    element.addEventListener('mouseup', function(){
        alert('clicked');
    });
  });
</script>
```

**Comment by peixotorms** [comment]
Thanks!

**Comment by shinsenter** [comment]
Hey @peixotorms 
If you want to launch a script when scrolling to an element on the page, then yes, you need to use the Defer.dom function. `observeOptions` is optional.

If you just lazy to load resources like js or css files then use Defer.js or Defer.css functions.

In case you need to delay running a JavaScript, use the Defer function.

All functions of Defer library are guaranteed to be executed as soon as your website has finished loading the page.
