### ISSUE TITLE
A callback feature must be added for transactions

### ISSUE THREAD

**Issue by ionurboz** [shinsenter/defer.js#73]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A callback feature must be added for transactions.

**Describe alternatives you've considered**
For example, it will be possible to add the uploaded CSS and JS files synchronously.

```js
Defer.js('https://connect.facebook.net/en_US/sdk.js', 'fb-sdk', 3000, callback);

function callback(){
    Defer.js('https://s7.addthis.com/js/300/addthis_widget.js', 'addthis_widget', 3000);
}
```

**Additional context**

**Comment by shinsenter** [comment]
Just do 
Defer.js('https://connect.facebook.net/en_US/sdk.js', 'fb-sdk', 3000, callback);
Defer.js('https://s7.addthis.com/js/300/addthis_widget.js', 'addthis_widget', 3000);
