### ISSUE TITLE
Renewability

### ISSUE THREAD

**Issue by ionurboz** [shinsenter/defer.js#78]
The `onload` and `onpageshow` events are normally ideal for the entire scenario.
But it should have a custom listener that allows us to use Defer.js with various frameworks.
For example, AngularJS, Turbolinks, pjax and so on.

```js
    window[_listen](
        'on' + _eventShow in window ? _eventShow : _attrLoadEvent,
        _proceedQueue
    );
    document[_listen](
        _attrCustomEvent,
        _proceedQueue
    );
```

**Comment by shinsenter** [comment]
@ionurboz 

I do not yet understand the specific situation where you want to combine defer.js and other render libraries like Angular.js. The purpose of defer.js is to help improve page load speed for webpages with regular HTML. For web pages rendered in JS, you might consider using [SSR](https://angular.io/guide/universal) instead of defer.js.

**Comment by ionurboz** [comment]
Actually, I don't mean a JavaScript parser.
Turbolinks, pjax, swup etc. Frames navigate pages with `XHR` requests using the `history API`, and the `DOM` remains static.

In such frameworks, when the new page is visited, the **JS, CSS** etc. fetches files and embeds them in the current `DOM`. But if we consider these to be `<script type = "deferjs"`, a new **JS** file added to the `DOM` will remain outside of **deferjs**'s perception. Because **deferjs** had worked once before. So it would be very good to listen to an event to run it over and over again asynchronously from the outside.

For detailed information, it is useful to take a look at [turbolinks.js](https://github.com/turbolinks/turbolinks) or [swup.js](https://swup.js.org/getting-started).

**Comment by shinsenter** [comment]
@ionurboz 

I think you can easily trigger loading `<script type="deferjs">` anywhere and anytime with `Defer.all()` method. Create your custom event and add `Defer.all` as the callback function.
https://github.com/shinsenter/defer.js#Defer.all

**Comment by ionurboz** [comment]
@shinsenter 
I can't believe I didn't see this. Thank you for your time. 🥇
