### ISSUE TITLE
Error with genesis + thrive

### ISSUE THREAD

**Issue by mickjaeger** [shinsenter/defer.js#79]
Check screenshot below for error after activating plugin using genesis 3.3.3 + thrive 2.6.7.4 framework 

wordpress version: 5.6.2
theme: magazine pro

https://www.screencast.com/t/AYtEEdhqFBXg

**Comment by shinsenter** [comment]
@mickjaeger 
May I have the URL of your website? It maybe a JS bug on the page.

**Comment by shinsenter** [comment]
@mickjaeger 
There were parser errors when parsing your javascript.
I have released v2.0.0-beta.27. Please give it a try. Thank you.
