### ISSUE TITLE
Issue with rank math sitemap.xml generator

### ISSUE THREAD

**Issue by mickjaeger** [shinsenter/defer.js#82]
Sitemap_index.xml generated by rank math is no longer working on the site with the plugin activated.

Sitemap is working fine if you disable plugin, Check screenshot below for the issue.

https://i.imgur.com/gLd8gDq.png

url: https://staging.continentalcamera.com/sitemap_index.xml

**Comment by shinsenter** [comment]
@mickjaeger 
which plugin version are you using?

**Comment by mickjaeger** [comment]
latest version, 2.0.0

**Comment by shinsenter** [comment]
@mickjaeger 
I could not open your staging URL. 
I will check it later on tomorrow.

Best regards

**Comment by mickjaeger** [comment]
https://staging.continentalcamera.com/

staging is working fine, the sitemap is blank/white because of the issue/error/bug. (https://staging.continentalcamera.com/sitemap_index.xml )

also version of rank math seo is 1.0.60.1

**Comment by shinsenter** [comment]
@mickjaeger 

I check your sitemap URL with some online sitemap validators, but it seems OK

**Comment by mickjaeger** [comment]
i think they were cache when the sitemap was working before installing the plugin. please review. thanks

**Comment by shinsenter** [comment]
@mickjaeger 
Your screenshot quality is not good, I could not see the error clearly. May I have a static result of the sitemap when defer.js plugin activated?

Paste this into Chrome's address bar
```
view-source:https://staging.continentalcamera.com/sitemap_index.xml
```

**Comment by mickjaeger** [comment]
check the screenshot below

https://www.screencast.com/t/CCSxPy4lJyQ

**Comment by shinsenter** [comment]
@mickjaeger 

I see. There is no problem with your sitemaps at all.
The errors in your screenshots came from the xsl file. 
FYI: An xsl file is used for transforming the xml to an human-readable format, in this case is an HTML page, then my plugin also optimized it.

I will consider a solution for this case.

**Comment by shinsenter** [comment]
@mickjaeger 

I have released a new version of the plugin. Try this new version to see if your problem gets solved.

**Comment by mickjaeger** [comment]
its solved/fixed now. thanks
