### ISSUE TITLE
Làm thế nào để mình sử dụng deferjs trên React

### ISSUE THREAD

**Issue by tuanducdesign** [shinsenter/defer.js#84]
Hiện tại thì mình đã dùng npm để install về rồi, giờ làm thế nào để cấu hình nó với các tệp js,css,img của React bạn nhỉ?

**Comment by shinsenter** [comment]
@tuanducdesign 
Còn tùy mục đích bạn muốn dùng như thế nào ạ.
Thư viện này chỉ giúp cho các trang web thông thường viết bằng mã HTML có thể tối ưu tốc độ tải trang bằng cách trì hoãn tải sau khi browser đã kết thúc việc render nội dung, sau cùng là tăng điểm SEO cho site dựa trên các tiêu chí đã có sẵn.

Đối với React hay bất cứ framework nào khác giúp render trang web bằng JS thì không áp dụng các rule này để cải thiện SEO mà cần phải dùng SSR để làm. Kết luận lại thư viện này không cần thiết đối với các ứng dụng web hay SPA viết hoàn toàn bằng React.

**Comment by tuanducdesign** [comment]
Okey thanks b
