### ISSUE TITLE
Defer.js của bạn có hỗ trợ defer google map khi nhúng từ Iframe k?

### ISSUE THREAD

**Issue by tuanducdesign** [shinsenter/defer.js#85]
Chào Mai Nhựt Tân! Defer.js của bạn có hỗ trợ defer google map khi nhúng từ Iframe k? và thư viện của bạn có thể kết hợp với lazysize k nhỉ? cảm ơn bạn.

**Comment by shinsenter** [comment]
@tuanducdesign 

Bạn có thể lazyload mọi thứ kể cả iframe và Google Maps API. Không cần thiết dùng lazysizes vì phần core của lazysizes khá nhiều phương thức phụ không cần thiết cho quá trình lazyload.

**Comment by shinsenter** [comment]
@tuanducdesign 
Bạn vẫn có thể dùng chung với lazysizes hoàn toàn không vấn đề gì, lazyloader nào chạy trước thì nó sẽ lazyload hình trước bằng lazyloader đó. Do mình cũng ko sure các bản cập nhật mới của lazysizes viết gì trong đó nên về tổng quát thì site của bạn có khả năng event sẽ bị trùng nếu dùng cùng lúc hai lazyloader.
