### ISSUE TITLE
DeferJS gặp lỗi với Rocket Loader của CloudFlare

### ISSUE THREAD

**Issue by tuanducdesign** [shinsenter/defer.js#88]
Chào Mai Nhựt Tân, Thư viện của bạn gặp lỗi với Rocket Loader của CloudFlare. Nếu mình tắt Rocket Loader đi thì lại bình thường, còn bật lên nó lại lỗi... K biết lỗi này do thư viện của bạn k tương thích với Rocket Loader của CloudFlare hay như nào nhỉ? Cảm ơn bạn trước.

**Comment by shinsenter** [comment]
@tuanducdesign 
Bạn có thể mô tả thêm cho mình về lỗi của bạn không? Vì nếu chỉ nói là lỗi thì rất khó cho mình tái hiện và phán đoán nguyên nhân từ đâu. Bạn có thể cung cấp một URL đến trang web đang xảy ra lỗi không? Hoặc tối thiểu cho mình biết tình trạng lỗi là gì, trên thẻ Console có hiện thông báo đỏ nào không (kèm screenshot).

Mình không rõ bạn có bật chức năng tối ưu hoá lazyload nào trên RocketLoader hay không, vì hai plugin cùng xử lý HTML để lazyload thì có khả năng cao sẽ xung đột.

Bạn cho mình thêm thông tin nhé
