### ISSUE TITLE
Ensure CSP is effective against XSS attacks 

### ISSUE THREAD

**Issue by tuanducdesign** [shinsenter/defer.js#91]
![Screen Shot 2021-06-18 at 20 21 15](https://user-images.githubusercontent.com/69758022/122567504-ef071500-d072-11eb-8e24-27b82228eae1.png)
Thư viện của bạn gặp lỗi như ảnh trên, k biết lỗi này do đâu bạn nhỉ?

**Comment by shinsenter** [comment]
@tuanducdesign 
Theo mình biết thì icon tròn màu xám ở đầu mục nghĩa là site của bạn đã vượt qua bài kiểm tra này, không phải là lỗi.

**Comment by tuanducdesign** [comment]
cái này giải quyết sao bạn nhỉ?

**Comment by shinsenter** [comment]
Thử nhấn Learn More màu xanh và tìm thêm cách làm mà bạn có thể xử lý nhé. Phần này là một trong các cập nhập từ Google chứ không phải lỗi từ plugin.

Nếu ko làm được thì cũng không sao cả vì hiện tại nó cũng ko ảnh hưởng.
